---
- hosts: database

  roles:
    - apt_mysql

  tasks:

    - name: Remove the MySQL test database.
      mysql_db: db=test state=absent

    - name: Create a database for Drupal.
      mysql_db: db=poc-base state=present
