---
- hosts: webserver

  pre_tasks:

    - include_vars:
        file: vars/vars.yml
      tags:
        - deploy

    - name: Ensure Node.js app folder exists.
      file: "path={{ node_apps_location }} state=directory"

  roles:

   - apt_nodejs
...
