---
- hosts: database

  roles:
    - apt_mysql

  tasks:

    - name: Remove the MySQL test database.
      mysql_db: db=test state=absent

    - name: Create a database for Drupal.
      mysql_db: db=poc-base state=present

    - name: Install python-mysql ans mysql
      apt: name={{ item }} state=present
      with_items:
         - python-mysqldb
         - mysql-server

    - name: Create database user
      mysql_user: user=ansible password=ansible priv=*.*:ALL state=present

    - name: Create database
      mysql_db: db=bdd1 state=present

    - name: Create database user
      mysql_user: user=ansible password=ansible priv=*.*:ALL state=present

    - name: Import data
      mysql_db: name=all state=import target= :/tmp/{{ inventory_hostname }}.sql
...

