---

- hosts: database

  vars_files:
    - vars.yml

  pre_tasks:

    - name: Copy sql file to server.
      copy: "src=data.sql dest=/tmp/data.sql"

  roles:

    - apt_mysql

  tasks:

    - name: Install python-mysql
      apt: name={{ item }} state=present
      with_items:
         - python-mysqldb

    - name: Remove the MySQL test database.
      mysql_db: db=test state=absent

    - name: Remove the MySQL poc-base database.
      mysql_db: db=poc-base state=absent

    - name: Create a database for POC.
      mysql_db: db=poc-base state=present
      notify:
        - Restart nodejs

    - name: Create database user
      mysql_user:
        name: ansible
        password: ansible
        host: 192.168.0.%
        priv: 'poc-base.*:ALL'
        state: present
      notify:
        - Restart nodejs

    - name: import data database with data.sql
      mysql_db: name=poc-base state=import target=/tmp/data.sql

  handlers:

    - name: Restart nodejs
      command: "forever restart {{ node_apps_location }}/app/app.js"
      failed_when: false
      delegate_to: "{{item}}"
      delegate_facts: True
      with_items: "{{groups['webserver']}}"

...
