---
- hosts: webserver

  tasks:
    - name: Check if port 80 is open
      wait_for: host={{ inventory_hostname }} port=80 timeout=5
      delegate_to: localhost

    - name: Check if static content of web page is OK.
      uri: 
        url: http://{{ inventory_hostname }}
        return_content: yes
      register: webpage_static

    - name: Static content test result...
      assert:
        that:
          - "'Hello World! I am {{ inventory_hostname }}' in webpage_static.content"
        msg: "There is a problem with static content."

    - name: Check if dynamic content of web page is OK.
      uri:
        url: http://{{ inventory_hostname }}
        return_content: yes
      register: webpage_dynamic

    - name: Dynamic content test result...
      assert:
        that:
          - "'Pipi' in webpage_dynamic.content"
        msg: "There is a problem with dynamic content (BDD)."

- hosts: database

  tasks:

    - name: Check if port 3306 is open
      wait_for: host={{ inventory_hostname }} port=3306 timeout=5
      delegate_to: localhost

    - name: Retrieve users from poc-base database.
      command: >
        mysql --user=ansible --password=ansible poc-base
        --host=192.168.0.103 --batch --skip-column-names
        --execute="SELECT * from user"
      register: user
      changed_when: False

    - name: Check the result of MySQL request
      assert:
        that:
          - "'Pipi' in user.stdout"
        msg: "'Pipi' not found in request result."

    - name: Check /etc/group contains "tata"
      command: grep -Fxq "tata" /etc/group
      register: checkuser
      check_mode: true
      ignore_errors: True
      changed_when: False

    - name: Display message if /etc/group contains "tata" "titi" "toto" "tutu" "tete"
      debug: msg="C'est bon!"
      when: checkuser == 0
...

