---

- hosts: webserver

  tasks:

    - name: check if port 80 is open
      shell: ss -tp state listening sport = :80
    - name: Get service on port 80
      shell: netstat -tunlp | grep ":80" | sed -e 's/.*\///'
      register: results
    - name: See what netstat returned
      debug: var=results
 
- hosts: database

  tasks:

    - name: check if port 3306 is open
      shell: ss -tp state listening sport = :3306
    - name: Get service on port 3306
      shell: netstat -tunlp | grep ":3306" | sed -e 's/.*\///'
      register: results
    - name: Retrieve user from mysql
      command: >
        mysql --user=ansible --password=ansible poc-base
        --host=192.168.0.103 --batch --skip-column-names
        --execute="SELECT * from user"
      register: user
      changed_when: False
    - name: Do something with user
      debug: "{{ item }}"
      with_items: user

    - name: Make sure connect to database
      mysql_db:
        login_user=ansible
        login_password=ansible
        login_host=192.168.0.103
        login_port=3306
        name=poc-base
        state=present
...
